### ISSUE TITLE
[Cohort #5] | PyCharm with source or VSC with Docker?

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#41]
### Question

I understand this is the main choice to make. First, am I right? Also, please explain the pros and cons of both approaches. My understanding (from a non-coder) is that PyCharm includes the architecture of the files/files/database and thus make live suggestions when writing the code, correct the syntax and also helps debug??
Can I achieve the same goal achieved with PyCharm but with a simpler/lighter version like VSC, which also adds the possibility to use CoPilot (an AI driven tool, like ChatGPT if I am correct). I would need a recommendation for a beginner/non-coder, thanks.

Additionally, has any beginnercoder experience with AI driven tools to write code?

**Comment by fengtality** [comment]
Both PyCharm and Visual Studio Code are [IDEs](https://en.wikipedia.org/wiki/Integrated_development_environment), basically code editors. Pycharm has better integration for Python-based codebases. 

VSC is more widely used as it's owned by Microsoft and supports Github Copilot. It's more beginner friendly.

AI-driven coding tools for anything crypto trading related is likely to be a waste of time since there hasn't been enough of a widely available trainable corpus.

**Comment by thenkinet** [comment]
Thank you, Michael. Sorry for the following question, but remember I am not a coder :;
Do I need to install Python at all? cloning the Hummingbot(-Botcamp) repository is all I need to install, along with Docker, right??
