### ISSUE TITLE
[Cohort #5] | Adaptative Multi-Agent Strategy (AMAS)

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#42]
### Question

The following very interesting paper is using Hummingbot: https://arxiv.org/abs/2204.13265. It is called "Adaptive Multi-Strategy Market-Making Agent for Volatile Markets".

Can you please help us achieving the same type of architecture, where several "agent" bots are run in parallel in a "testing mode" and then their performances are passed to a "master bot" which decides to select the best one based on some metrics, to use in a live trading environment, for the next period. Perhaps the new 'two-way" Hummingbot module called "Broker" (or Orchestrator) is intended for that purpose (among other things). Please confirm.

However, the interview with Eugene Tartakovsky (from 3Jane in Moscow) [https://www.youtube.com/watch?v=E2p4T2R9cGo - around minute 14 - btw the best video of the series, I strongly recommend anyone to watch it] suggested this type of approach, he called "walk forward optimisation", was not working well or maybe the two approaches are rely different. Please help me to understand.

Thanks!

NB. Eugene has used "statistical arbitrage", a type of mean-reverting trading strategy perfectly adapted to the Hummingbot know-how, if I am correct. Maybe an idea for a future module or strategy ;)

**Comment by fengtality** [comment]
I can go into more details during Office Hours on how to achieve that type of multi-agent architecture. Generally, it's definitely possible using the Brokers module along with some Docker configuration skills, but it's also a highly custom architecture that can't really be built "out of the box."

The main lesson I would draw is that there is A LOT of complexity that goes into deploying a full-scale trading system that can adapt and learn to ever-changing market conditions. I think what Eugene is saying in that video is that there are many theoretical approaches toward optimization that they found didn't work well in practice, but other techniques worked better. A lot of their success, in my opinion, is because they have really good engineers who are fine-tuning every aspect of their system.

**Comment by thenkinet** [comment]
Not need for further explanations at this point, as I will probably get lost in the explanations. I just needed to know if it was possible. You replied perfectly, so thanks!
